###
GET http://localhost:4004/system
Authorization: Basic bob:PW
###
GET http://localhost:4004/system/Environments
Authorization: Basic bob:PW
###
GET http://localhost:4004/system/Environments
Authorization: Basic alice:PW
###
GET http://localhost:4004/system/User
Authorization: Basic bob:PW
